version: '2'
services:
    proxy:
        container_name: proxy
        build: ./httpd-proxy
        image: acheype/httpd-proxy
        links:
            - "www:www"
            - "webdav:webdav"
            - "lizmap:lizmap"
            - "wiki:wiki"
        ports:
            - "80:80"
    www:
        container_name: www
        build: ./httpd-www
        image: acheype/httpd-www
        volumes:
            - /data/www:/var/www/html
    webdav:
        container_name: webdav
        build: ./httpd-webdav
        image: acheype/httpd-webdav
        volumes:
            - /data/webdav:/var/webdav
    lizmap:
        container_name: lizmap
        build: ./lizmap
        image: acheype/lizmap
        volumes:
            - /data/webdav/lizmap:/home
            - /data/lizmap_var:/var/www/websig/lizmap/var
            - /data/lizmap_tmp:/tmp
    wiki:
        container_name: wiki
        image: kristophjunge/mediawiki:1.28
        environment:
          MEDIAWIKI_SERVER: http://wiki.data-pacifique.ird.nc
          MEDIAWIKI_SITENAME: Wiki du portail de données - IRD Nouméa
          MEDIAWIKI_LANGUAGE_CODE: fr
          MEDIAWIKI_SECRET_KEY: mysecretkey
          MEDIAWIKI_DB_TYPE: mysql
          MEDIAWIKI_DB_HOST: mysql
          MEDIAWIKI_DB_PORT: 3306
          MEDIAWIKI_DB_NAME: wikidb
          MEDIAWIKI_DB_USER: wikiuser
          MEDIAWIKI_DB_TABLE_OPTIONS: ENGINE=InnoDB, DEFAULT CHARSET=utf8
          MEDIAWIKI_DB_PASSWORD: $MEDIA_WIKI_DB_PWD
          MEDIAWIKI_ENABLE_UPLOADS: 1
          MEDIAWIKI_ENABLE_VISUAL_EDITOR: 1
          MEDIAWIKI_DEFAULT_SKIN: vector
        links:
            - mysql:mysql
        volumes:
            - /data/wiki/images:/images
            - ./mediawiki/logo_IRD.png:/var/www/mediawiki/resources/assets/wiki.png:ro
            - ./mediawiki/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro
    mysql:
        container_name: mysql
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: wikidb
            MYSQL_USER: wikiuser
            MYSQL_PASSWORD: $MEDIA_WIKI_DB_PWD
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PWD
        volumes:
            - /data/wiki/mysql:/var/lib/mysql
        ports:
            - 3306:3306
